支持继承类修改网络访问方法
dotnet-campus/dotnetCampus.FileDownloader pull request #25
Opened 2020-10-14 11:42 UTC by lindexi

https://github.com/dotnet-campus/dotnetCampus.FileDownloader/issues/23

可以用来设置代理，可以设置缓存下载或者其他定制

2020-10-16 00:51 UTC, walterlv requested changes

2020-10-16 00:51 UTC, walterlv commented on src/dotnetCampus.FileDownloader/SegmentFileDownloader.cs
> +        protected virtual HttpWebRequest CreateWebRequest(string url) => (HttpWebRequest)WebRequest.Create(url);
我被逗了？我了解到的是，因为 .NET 不内置代理，所以即便你写了这个虚方法也无法完成你期望的设置代理吧……

2020-10-16 03:57 UTC, kkwpsv commented on src/dotnetCampus.FileDownloader/SegmentFileDownloader.cs
> +        protected virtual HttpWebRequest CreateWebRequest(string url) => (HttpWebRequest)WebRequest.Create(url);
继承类重写就可以设置了吧....HttpWebRequest.Proxy属性来改

2020-10-17 03:22 UTC, lindexi commented on src/dotnetCampus.FileDownloader/SegmentFileDownloader.cs
> +        protected virtual HttpWebRequest CreateWebRequest(string url) => (HttpWebRequest)WebRequest.Create(url);
@walterlv 如 @kkwpsv 所说

2020-10-24 08:54 UTC, merged