基础能用的版本
dotnet-campus/dotnetCampus.FileDownloader pull request #4
Opened 2020-07-20 00:59 UTC by lindexi

2020-07-20 02:45 UTC, lindexi commented
![图片](https://user-images.githubusercontent.com/16054566/87894682-06f6a300-ca76-11ea-8909-6f68e09c0f7e.png)

2020-07-29 07:21 UTC, walterlv requested changes

2020-07-29 07:21 UTC, walterlv commented on src/dotnetCampus.FileDownloader.Tool/FileSizeFormatter.cs
> +        public static string FormatSize(double bytes, string formatString = "{0:0.00}{1}")
```suggestion
        /// <summary>
        /// 获取字节数的格式化字符串。因为可能存在“平均字节数”，所以支持小数。
        /// </summary>
        public static string FormatSize(double bytes, string formatString = "{0:0.00}{1}")
```

2020-07-29 07:21 UTC, walterlv commented on src/dotnetCampus.FileDownloader.Tool/dotnetCampus.FileDownloader.Tool.csproj
> +        <ToolCommandName>FileDownloader</ToolCommandName>
这种类型的工具名是不是弄个动词会好些？比如 DownloadFile、curl 之类？

2020-07-29 07:21 UTC, walterlv commented on src/dotnetCampus.FileDownloader/RandomFileWriter.cs
> +        public event EventHandler<byte[]> StepWriteFinished = delegate { };
实践中，倾向于放 EventArgs 类型
[标准 .NET 事件模式 | Microsoft Docs](https://docs.microsoft.com/zh-cn/dotnet/csharp/event-pattern)

2020-07-29 07:21 UTC, walterlv commented on src/dotnetCampus.FileDownloader/RandomFileWriter.cs
> +                    throw Exception;
```suggestion
                    ExceptionDispatchInfo.Capture(Exception).Throw();
```

2020-08-04 06:38 UTC, walterlv requested changes

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader/Progress_/FileDownloadSpeedProgress.cs
> +            public bool IsFinished => DownloadProgress.DownloadedLength == DownloadProgress.FileLength;
之前有一些软件会出现下载比特数已超最大大小却依然继续下载，实际文件早已错误的情况。所以建议这里写 `>=`

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader.WPF/ContentDialog.xaml.cs
> +        public event EventHandler Closed = null!;
```suggestion
        public event EventHandler? Closed;
```

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader.WPF/ContentDialog.xaml.cs
> +            Closed(this, EventArgs.Empty);
```suggestion
            Closed?.Invoke(this, EventArgs.Empty);
```

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader.WPF/DownloadFileInfo.cs
> +        public event PropertyChangedEventHandler PropertyChanged;
```suggestion
        public event PropertyChangedEventHandler? PropertyChanged;
```

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader.WPF/DownloadFileManager.cs
> +        public async Task<List<DownloadFileInfo>> ReadDownloadedFileList()
```suggestion
        public async Task<List<DownloadFileInfo>> ReadDownloadedFileListAsync()
```

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader.WPF/DownloadFileManager.cs
> +            var file = Path.Combine(folder!, StorageFile);
已经 ! 一次了

2020-08-04 06:38 UTC, walterlv commented on src/dotnetCampus.FileDownloader.WPF/dotnetCampus.FileDownloader.WPF.csproj
> +		<PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.6"></PackageReference>
```suggestion
        <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.6" />
```

2020-08-04 12:43 UTC, merged